### ISSUE TITLE
记录一种播放时没有声音的情况。

### ISSUE THREAD

**Issue by myDonghao** [ihoudf/DFPlayer#29]
我这边是一个录音播放，上传，然后回显的逻辑。
在我的录音功能中修改了
`
    [[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryPlayAndRecord error:nil];
    [[AVAudioSession sharedInstance] setActive:YES error:nil];
`
然后DFPlayer中因为是在初始化的时候设置的这个Category
所以在录音开启后，DFPlayer中的Category没有改变,因此建议在播放的时候重置一下这个
`
    [[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryPlayback error:nil];
    [[AVAudioSession sharedInstance] setActive:YES error:nil];
`

**Comment by ihoudf** [comment]
> 我这边是一个录音播放，上传，然后回显的逻辑。
> 在我的录音功能中修改了
> `[[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryPlayAndRecord error:nil]; [[AVAudioSession sharedInstance] setActive:YES error:nil];`
> 然后DFPlayer中因为是在初始化的时候设置的这个Category
> 所以在录音开启后，DFPlayer中的Category没有改变,因此建议在播放的时候重置一下这个
> `[[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryPlayback error:nil]; [[AVAudioSession sharedInstance] setActive:YES error:nil];`

可以手动更改。    [DFPlayer sharedPlayer].category = AVAudioSessionCategoryPlayback;
[[AVAudioSession sharedInstance] setActive:YES error:nil];
这样试试。

**Comment by myDonghao** [comment]
嗯，昨天我也是忽然想到没有声音可能是这个原因，记录一下，给大伙儿提供一个思路。
